[project]
name = "elasticsearch-documentation-manager-mcp"
version = "0.1.0"
description = "An MCP server for crawling documentation, writing it to Elasticsearch for vector search retrieval by an LLM."
authors = [
    {name = "strawgate",email = "williamseaston@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elasticsearch (>=8.17.2,<9.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "anyio (>=4.9.0,<5.0.0)",
    "fastmcp>=0.4.1",
    "aiohttp>=3.11.14",
    "docker"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = "^0.11.2"

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]


[tool.poetry]
packages = [
    { include = "elasticsearch-documentation-manager-mcp" },
    { include = "elasticsearch-documentation-manager-mcp/**/*.py" },
]
